# Name
site_name: Ellipsis-__name__

# Docs directory
docs_dir: docs

# Docs page index
pages:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - About: about.md

# Theme
theme: readthedocs
